"""empty message

Revision ID: 603a1bc8f9be
Revises: 0d8d08f7ead6
Create Date: 2024-04-12 14:28:50.890048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603a1bc8f9be'
down_revision = '0d8d08f7ead6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###
