"""empty message

Revision ID: 7580b828e9d6
Revises: 3de0691a931e
Create Date: 2024-04-09 15:39:19.291423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7580b828e9d6'
down_revision = '3de0691a931e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('update_date')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('update_date')

    # ### end Alembic commands ###
