"""empty message

Revision ID: f9853b8b0922
Revises: 603a1bc8f9be
Create Date: 2024-04-12 14:36:14.033711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9853b8b0922'
down_revision = '603a1bc8f9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
