"""empty message

Revision ID: 321724805412
Revises: 4341b50a5f7c
Create Date: 2024-04-12 09:34:28.841196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321724805412'
down_revision = '4341b50a5f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
